services:
  baserow:
    container_name: baserow
    image: baserow/baserow:1.35.1
    environment:
      BASEROW_PUBLIC_URL: "https://db.slc.asso.fr"
      # pas besoin de WEB_FRONTEND_SSL_PORT si Caddy gère le SSL
    volumes:
      - baserow_data:/baserow/data
    networks:
      - web-network
    restart: unless-stopped
    expose:
      - "80"

volumes:
  baserow_data:

networks:
  web-network:
    external: true